name: Test

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/pages.yml'
      - '.github/page-template.html'
      - 'web-store-submissions/**'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/pages.yml'
      - '.github/page-template.html'
      - 'web-store-submissions/**'
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Run build
      run: npm run build